#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Recompute ``assessments/progress.md`` from ``assessments/responses.jsonl``.

Reads the append-only log, computes per-module counts and average
understanding level, derives status (``not started`` / ``in progress`` /
``passed``), and rewrites ``progress.md``. Also surfaces open gaps and
recurring strengths in dedicated sections so the agent can spot them at a
glance before the next assessment.

The module list shown in the table is discovered from two sources:
  1. Directory listing of ``<curriculum_dir>/modules/*.md`` (authoritative order).
  2. Any module names that appear in the JSONL but not on disk (listed after,
     typically synthesis prompts).

Emits a structured JSON summary on stdout.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

PASS_THRESHOLD = 3.0


def emit(payload: dict) -> None:
    print(json.dumps(payload))


def module_slug_from_path(p: Path) -> str:
    return p.stem


def derive_status(count: int, avg_level: float | None) -> str:
    if count == 0:
        return "not started"
    if avg_level is not None and avg_level >= PASS_THRESHOLD:
        return "passed"
    return "in progress"


def load_rows(jsonl_path: Path) -> list[dict]:
    rows: list[dict] = []
    if not jsonl_path.exists():
        return rows
    with jsonl_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return rows


def summarize_modules(rows: list[dict], disk_modules: list[str]) -> list[tuple[str, dict]]:
    by_mod: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        mod = row.get("module")
        if isinstance(mod, str):
            by_mod[mod].append(row)

    ordered: list[str] = []
    seen: set[str] = set()
    for m in disk_modules:
        ordered.append(m)
        seen.add(m)
    for m in sorted(by_mod.keys()):
        if m not in seen:
            ordered.append(m)
            seen.add(m)

    out: list[tuple[str, dict]] = []
    for mod in ordered:
        module_rows = by_mod.get(mod, [])
        count = len(module_rows)
        levels = [
            r["assessment"]["understanding_level"]
            for r in module_rows
            if isinstance(r.get("assessment"), dict)
            and isinstance(r["assessment"].get("understanding_level"), int)
        ]
        avg = round(sum(levels) / len(levels), 2) if levels else None
        last_ts = max(
            (r["timestamp"] for r in module_rows if isinstance(r.get("timestamp"), str)),
            default=None,
        )
        status = derive_status(count, avg)
        out.append(
            (
                mod,
                {
                    "count": count,
                    "avg_level": avg,
                    "last_activity": last_ts,
                    "status": status,
                },
            )
        )
    return out


def collect_gaps(rows: list[dict]) -> list[tuple[str, int]]:
    counter: Counter[str] = Counter()
    resolved: set[str] = set()

    def fingerprint(text: str) -> str:
        return text.strip().lower()

    for row in rows:
        assessment = row.get("assessment") or {}
        adaptation = row.get("adaptation") or {}

        level = assessment.get("understanding_level")
        if isinstance(level, int) and level >= PASS_THRESHOLD:
            for g in assessment.get("strengths", []) or []:
                if isinstance(g, str):
                    resolved.add(fingerprint(g))

        for g in adaptation.get("revisit_before_next_module", []) or []:
            if isinstance(g, str):
                counter[fingerprint(g)] += 1

    open_gaps = [(gap, count) for gap, count in counter.most_common() if gap not in resolved]
    return open_gaps


def collect_strengths(rows: list[dict]) -> list[tuple[str, int]]:
    counter: Counter[str] = Counter()
    for row in rows:
        assessment = row.get("assessment") or {}
        for s in assessment.get("strengths", []) or []:
            if isinstance(s, str):
                counter[s.strip().lower()] += 1
    return [(s, n) for s, n in counter.most_common() if n >= 2]


def render(
    module_rows: list[tuple[str, dict]],
    open_gaps: list[tuple[str, int]],
    strengths: list[tuple[str, int]],
) -> str:
    lines: list[str] = [
        "# Progress Tracker",
        "",
        "Regenerated by `compute_progress.py` from `assessments/responses.jsonl`.",
        "",
        "| Module | Status | Last Activity | Avg. Understanding Level | Questions Logged |",
        "|--------|--------|---------------|--------------------------|------------------|",
    ]
    if not module_rows:
        lines.append("| (no modules recorded yet) | — | — | — | 0 |")
    else:
        for mod, info in module_rows:
            avg = info["avg_level"]
            avg_str = f"{avg:.2f}" if avg is not None else "—"
            last = info["last_activity"] or "—"
            lines.append(
                f"| {mod} | {info['status']} | {last} | {avg_str} | {info['count']} |"
            )

    lines += ["", "## Open Gaps", ""]
    if not open_gaps:
        lines.append("(no open gaps recorded)")
    else:
        for gap, count in open_gaps:
            lines.append(f"- ({count}x) {gap}")

    lines += ["", "## Recurring Strengths", ""]
    if not strengths:
        lines.append("(none yet — strengths recur here once they appear in ≥2 assessments)")
    else:
        for strength, count in strengths:
            lines.append(f"- ({count}x) {strength}")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--curriculum-dir",
        required=True,
        help="Absolute path to the curriculum directory.",
    )
    args = parser.parse_args()

    curriculum_dir = Path(args.curriculum_dir).expanduser().resolve()
    jsonl_path = curriculum_dir / "assessments" / "responses.jsonl"
    progress_path = curriculum_dir / "assessments" / "progress.md"
    modules_dir = curriculum_dir / "modules"

    if not modules_dir.is_dir() or not jsonl_path.parent.is_dir():
        emit(
            {
                "success": False,
                "error": "curriculum_not_scaffolded",
                "curriculum_dir": str(curriculum_dir),
                "hint": "Run scaffold.py first.",
            }
        )
        return 2

    disk_modules = sorted(module_slug_from_path(p) for p in modules_dir.glob("*.md"))

    rows = load_rows(jsonl_path)
    module_rows = summarize_modules(rows, disk_modules)
    open_gaps = collect_gaps(rows)
    strengths = collect_strengths(rows)

    progress_path.write_text(render(module_rows, open_gaps, strengths))

    emit(
        {
            "success": True,
            "progress_path": str(progress_path),
            "row_count": len(rows),
            "module_count": len(module_rows),
            "passed_modules": [m for m, info in module_rows if info["status"] == "passed"],
            "in_progress_modules": [
                m for m, info in module_rows if info["status"] == "in progress"
            ],
            "open_gap_count": len(open_gaps),
        }
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
