#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Initialize a curriculum output directory.

Creates the directory structure and copies the topic-agnostic template files
from the skill's ``assets/`` directory. Does not write ``README.md`` or any
module files — those are topic-specific and the agent writes them after
scaffolding.

Exits with a non-zero code and a structured JSON error on stdout if the
output directory already exists and is non-empty. The agent must ask the
user how to proceed before overriding.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = SKILL_DIR / "assets"


def emit(payload: dict) -> None:
    print(json.dumps(payload))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Absolute path where the curriculum will be written.",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir).expanduser().resolve()

    if output_dir.exists() and any(output_dir.iterdir()):
        emit(
            {
                "success": False,
                "error": "output_dir_exists_nonempty",
                "output_dir": str(output_dir),
                "hint": "Ask the user whether to overwrite, pick a different path, or abort.",
            }
        )
        return 2

    modules_dir = output_dir / "modules"
    assessments_dir = output_dir / "assessments"
    modules_dir.mkdir(parents=True, exist_ok=True)
    assessments_dir.mkdir(parents=True, exist_ok=True)

    src_meta = ASSETS_DIR / "curriculum-meta.md"
    src_miscon = ASSETS_DIR / "assessments" / "misconceptions.md"
    if not src_meta.exists() or not src_miscon.exists():
        emit(
            {
                "success": False,
                "error": "missing_asset",
                "hint": f"Expected {src_meta} and {src_miscon} to exist in the skill.",
            }
        )
        return 3

    shutil.copyfile(src_meta, output_dir / "curriculum-meta.md")
    shutil.copyfile(src_miscon, assessments_dir / "misconceptions.md")

    (assessments_dir / "responses.jsonl").write_text("")

    created_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    progress_content = (
        "# Progress Tracker\n\n"
        "Regenerated by `compute_progress.py` after each assessment append.\n"
        f"Initialized on {created_at}.\n\n"
        "| Module | Status | Last Activity | Avg. Understanding Level |\n"
        "|--------|--------|---------------|--------------------------|\n"
        "| (no modules recorded yet) | — | — | — |\n\n"
        "## Open Gaps\n\n"
        "(populated after first assessment)\n\n"
        "## Recurring Strengths\n\n"
        "(populated after first assessment)\n"
    )
    (assessments_dir / "progress.md").write_text(progress_content)

    emit(
        {
            "success": True,
            "output_dir": str(output_dir),
            "created": [
                str(output_dir / "curriculum-meta.md"),
                str(modules_dir),
                str(assessments_dir / "responses.jsonl"),
                str(assessments_dir / "progress.md"),
                str(assessments_dir / "misconceptions.md"),
            ],
            "next_steps": [
                "Write README.md with the approved module map.",
                "Write each modules/NN-*.md following references/module-template.md.",
            ],
        }
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
